version: "3.9"
services:
  node:
    image: naterkana/omsv2-backend:0.3
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      NODE_OPTIONS: --max-old-space-size=4096
      TZ: 'Asia/Bangkok' 
    volumes:
      - /path/on/host:/path/in/container
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - node-backend
  
networks:
  node-backend:
    driver: bridge